### ISSUE TITLE
How to implement

### ISSUE THREAD

**Issue by blakenorthrup** [CarlEdman/godaddy-ddns#9]
Hi CarlEdman, this script looks great, but I'm a total noob, and it have 0 idea of how to implement this. Do you have a walk-through on this?

**Comment by CarlEdman** [comment]
Sure.  I guess the lack of proper documentation for newbies is a real issue.  What you need:

1. A GoDaddy-registered domain.  I assume you already have that.  Let's call it bar.com.

2. Create an A record under your domain for your home IP.  Let's give it the name foo, so in the end you'll be able to access the IP address of your home as foo.bar.com.  You can create that A record under DNS Management at the GoDaddy web site.  Setting the TTL (time to live) to the default of 1 hour is fine, but you may want to reduce it to the minimum while you experiment with the set up.  Give it a dummy IP address.

3. Next you need your GoDaddy API Key and Secret.  Go to https://developer.godaddy.com/keys and create a new API Key and Secret and note them down somewhere.  In particular, the secret appears to be unrecoverable if you lose it.  I'll call them KEY and SECRET below.

4. A device to run the godaddy-ddns script on.  Anything on your home network that can run Python 3 will be fine.  I run it directly on my OpenWRT router, which has some advantages, but requires a relatively powerful and customized router.

5. If you have all that, install the godaddy-ddns on your device and create a config file with the following content:
```
foo.bar.com
--key
KEY
--secret
SECRET
```
You'll of course insert the appropriate values for your host/domain/key/secret.  The line breaks in the config file are necessary.

6. Now you can automatically update the external IP address of your home network by running
`/path/to/godaddy_ddns.py %/path/to/config`

One of the advantages of running the script on your router is that you can then configure the router to run the script automatically whenever the router the reboots and/or the public IP address changes, but how exactly to do that depends on your router.  Otherwise just run it periodically from anywhere within your network.

7. Test that your record was updated properly, e.g., by running
`nslookup foo.bar.com`
After the script runs successfully it should point to your home network.  If there is some screwup, the wrong value may be cached by up to the TTL you gave above, so even if you make a correction it won't show up for that period of time.  That is the reason I suggested setting the TTL low until you are sure you got it right.

Hope this was understandable and helps!  I really should put this into the docs and won't close this comment until I have.

**Comment by blakenorthrup** [comment]
Thank you so much for the fast reply, and you’re right. Us noobs are looking a Greek sometimes when looking at these repositories.

**Comment by CarlEdman** [comment]
And done.
